name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        pip install -r farm/requirements.txt

    - name: Use SSH private key
      run: |
        mkdir -p $HOME/.ssh/DigitalOcean_ssh_barrybuntu
        echo "${{ secrets.DEPLOY_KEY }}" > $HOME/.ssh/DigitalOcean_ssh_barrybuntu/id_rsa
        chmod 600 $HOME/.ssh/DigitalOcean_ssh_barrybuntu/id_rsa

    - name: Update known_hosts file
      run: |
        mkdir -p $HOME/.ssh
        ssh-keyscan -t rsa 165.22.89.227 >> $HOME/.ssh/known_hosts

    - name: Run Tests
      run: |
        pytest farm/test_main.py

    - name: Deploy to VPS
      if: success()
      run: |
        chmod +x deploy.sh
        ./deploy.sh

    - name: Restart Gunicorn
      if: success()
      run: |
        ssh -i $HOME/.ssh/DigitalOcean_ssh_barrybuntu/id_rsa root@165.22.89.227 'sudo systemctl restart farm'
