name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    #- name: Install Dependencies
     # run: |
      #  pip install -r farm/requirements.txt
    - name: Print Environment
      run: |
        echo "Home Directory: $HOME"
        echo "SSH Private Key Path: $HOME/.ssh/DigitalOcean_ssh_barrybuntu/id_rsa"
        echo "Environment Variables:"
        env
        ls -l $HOME/.ssh/DigitalOcean_ssh_barrybuntu/id_rsa
    - name: Run Tests
      run: |
        pytest farm/test_main.py

    - name: Deploy to VPS
      if: success()
      run: |
        chmod +x deploy.sh
        ./deploy.sh
